apiVersion: v1
kind: Service
metadata:
  labels:
    app: froneend
  name: front-svc
spec:
  ports:
  - port: 8989
    protocol: TCP
    targetPort: 5173
  selector:
    app: froneend
  type: LoadBalancer
status:
  loadBalancer: {}
