apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bdtaskpod.yaml
- front-svc.yaml
images:
- name: argo-app
  newName: /bdtask
  newTag: "20231221193340"
- name: bdtask
  newName: "20231221195248"
